// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttjnbcmgxotfzzcibwux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0am5iY21neG90Znp6Y2lid3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTk1NzAsImV4cCI6MjA3MDU3NTU3MH0.vAvF3uT1hiAvrgPKxnB5s_JkCQyb2stU9DoHOJWGntg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});